name: Deploy Elasticsearch Visualizations

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Load data to Elasticsearch
      env:
        ELASTIC_ID: ${{ secrets.ELASTIC_ID }}
        ELASTIC_PASSWD: ${{ secrets.ELASTIC_PASSWD }}
      run: |
        echo "=== Debug: Variables de entorno ==="
        echo "Cloud ID length: ${#ELASTIC_ID}"
        echo "Password length: ${#ELASTIC_PASSWD}"
    
        # Verifica que las variables existen
        if [ -z "$ELASTIC_ID" ]; then
          echo "::error::ELASTIC_ID está vacío"
          exit 1
        fi
    
        if [ -z "$ELASTIC_PASSWD" ]; then
          echo "::error::ELASTIC_PASSWD está vacío"
          exit 1
        fi
    
        python scripts/load_to_elasticsearch.py
    
    - name: Generate visualizations
      env:
        ELASTIC_ID: ${{ secrets.ELASTIC_ID }}
        ELASTIC_PASSWD: ${{ secrets.ELASTIC_PASSWD }}
      run: |
        python scripts/visualize.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
