name: Deploy Elasticsearch Visualizations

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Load data to Elasticsearch
      env:
        ELASTIC_ID: ${{ secrets.ELASTIC_ID }}
        ELASTIC_PASSWD: ${{ secrets.ELASTIC_PASSWD }}
      run: |
        echo "Verificando variables de entorno..."
        echo "Cloud ID length: ${#ELASTIC_CLOUD_ID}"  # No muestra el valor real
        echo "Password length: ${#ELASTIC_PASSWORD}"  # No muestra el valor real
        python scripts/load_to_elasticsearch.py
    
    - name: Generate visualizations
      env:
        ELASTIC_CLOUD_ID: ${{ secrets.ELASTIC_ID }}
        ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWD }}
      run: |
        python scripts/visualize.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
